/*
-- Query: SELECT 
AssessmentAnswer_id,
answer,
question,
topic

 FROM jac.assessmentanswercollection
-- Date: 2025-05-25 19:37
*/
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,1,1,'Scientific Notation');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,2,2,'Pythagoras Theorem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,3,3,'Index');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,2,4,'Percentage');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,1,5,'Money');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,2,6,'Simple Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,1,7,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,4,8,'Inequality');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,3,9,'Volume');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,2,10,'Inequality');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,1,11,'Sine Rule');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,2,12,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,3,13,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,3,14,'Tangent');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,1,15,'Equation of Line');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,3,16,'Equation of Line');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,3,17,'Number Line');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,2,18,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,4,19,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (2,2,20,'Angles');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,4,1,'Percentage');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,3,2,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,2,3,'Algebraic Expression');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,3,4,'Time');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,2,5,'Pythagoras Theorem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,1,6,'Alternate Angles');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,4,7,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,1,8,'Area');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,2,9,'Index numbers');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,4,10,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,4,11,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,4,12,'Square');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,2,13,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,3,14,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,3,15,'Perimeter');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,4,16,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,2,17,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,1,18,'Length (diamter)');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,3,19,'Operation');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (3,3,20,'Area of Circle');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,1,1,'Order');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,4,2,'Shape');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,2,3,'Percentrage');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,3,4,'Mixed Operations');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,4,5,'Inequality');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,1,6,'Decimal Subtraction');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,3,7,'Number Sentence');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,4,8,'Triangle');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,3,9,'Fraction');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,1,10,'Common Multiple');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,3,11,'Fraction Addition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,2,12,'Isosceles Triangle');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,1,13,'Negative Number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,3,14,'Numbers');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,2,15,'Squares');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,3,16,'Index Operation');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,1,17,'Algebra');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,2,18,'Algebraic Expression');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,2,19,'Symmetry');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (4,2,20,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,3,1,'Numeration');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,3,2,'Time and cost');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,3,'Number pattern');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,4,'Even and odd');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,3,5,'Pattern');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,1,6,'Problem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,7,'Unknown number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,3,8,'Company height');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,9,'Weight');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,10,'Missing number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,11,'Problem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,3,12,'Arranging numbers');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,3,13,'Product');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,1,14,'Area');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,3,15,'Age');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,1,16,'Estimate');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,1,17,'Conversion');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,18,'Perimter');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,4,19,'Problem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (5,2,20,'Harder problem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,3,1,'Place value');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,2,'Statement');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,4,3,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,4,'Money');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,1,5,'Volume');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,6,'Decimal');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,3,7,'Rounding off');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,3,8,'Perimeter');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,4,9,'Age');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,4,10,'Volume');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,11,'Estimate');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,1,12,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,13,'Money');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,4,14,'Area');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,3,15,'Parallel lines');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,3,16,'Perimeter');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,17,'Mass (Weight)');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,18,'Missing number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,4,19,'Capacity');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (6,2,20,'Decimal number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,4,1,'Largest number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,3,2,'Number pattern');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,2,3,'Money');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,3,4,'Numeration');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,2,5,'Missing number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,2,6,'Perimter');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,3,7,'Angle');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,2,8,'Distance');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,1,9,'Rounding off');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,4,10,'Multiples');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,1,11,'Factors');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,3,12,'Place value');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,4,13,'Statement');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,2,14,'Equivalent fraction');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,1,15,'Fraction');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,1,16,'Time');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,3,17,'Dates');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,3,18,'Statement');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,4,19,'Area');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (7,1,20,'Length');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,3,1,'Greatest value');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,2,2,'Remainder');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,1,3,'Length');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,2,4,'Money');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,4,5,'Missing number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,3,6,'Graph');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,2,7,'Graph');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,1,8,'Graph');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,2,9,'Number pattern');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,3,10,'Numeration');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,4,11,'Angles');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,3,12,'Area');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,4,13,'Perimeter');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,2,14,'Missing fraction');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,1,15,'Fraction');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,3,16,'Time');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,2,17,'Days');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,2,18,'Money problem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,3,19,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (8,3,20,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,2,1,'Number in word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,3,2,'Numeration');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,4,3,'Addition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,4,4,'Middle number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,2,5,'Missing number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,2,6,'Division');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,2,7,'Multiplication');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,1,8,'More than');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,4,9,'Less than');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,3,10,'Missing signs');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,1,11,'Longest');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,2,12,'Number pattern');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,1,13,'Missing number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,3,14,'Tallest');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,2,15,'Time');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,3,16,'Money problem');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,2,17,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,3,18,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,4,19,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (9,1,20,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,3,1,'Number in word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,2,'Word in numeral');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,3,'Addition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,3,4,'Substraction');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,5,'Missing number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,1,6,'Number in order');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,7,'Middle number');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,3,8,'Number in order');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,1,9,'Triangle');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,10,'Position');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,11,'Length');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,4,12,'Length');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,4,13,'Total length');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,14,'Mass');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,2,15,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,4,16,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,4,17,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,1,18,'Problem solving');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,1,19,'Position');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (10,1,20,'Addition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,1,'Word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,2,'Reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,3,'Word meaning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,4,4,'Numeration sequence');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,5,'Opposite');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,1,6,'Reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,7,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,4,8,'Grouping word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,9,'Description');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,10,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,2,11,'Spatial reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,1,12,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,13,'Grouping word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,14,'Numeration sequence');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,4,15,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,16,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,17,'Letters');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,4,18,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,3,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (11,1,20,'Sequence of letters');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,1,1,'Spatial reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,3,2,'Word meaning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,2,3,'Opposite');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,4,4,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,1,5,'Numerical sequence');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,1,6,'Letters');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,3,7,'Numerical reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,2,8,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,2,9,'Grouping word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,4,10,'Proverb');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,1,11,'Spatial reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,2,12,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,3,13,'Grouping word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,3,14,'Reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,3,15,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,2,16,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,4,17,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,1,18,'Similar reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,2,19,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (12,2,20,'Proverb');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,2,1,'Surface area');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,2,2,'Letter');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,1,3,'Numerical sequence');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,3,4,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,2,5,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,3,6,'Geography');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,3,7,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,1,8,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,2,9,'Word Association');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,1,10,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,3,11,'Sequence');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,4,12,'Numerical reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,1,13,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,3,14,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,4,15,'Reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,4,16,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,3,17,'Grouping word');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,2,18,'Numerical reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,2,19,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (13,2,20,'Proverb');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,2,1,'Verbal (synonym)');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,1,2,'Numerical reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,2,3,'Verbal');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,4,4,'Numerical reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,4,5,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,6,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,2,7,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,8,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,2,9,'Odd one');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,10,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,11,'Meaning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,2,12,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,13,'Analogy');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,14,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,15,'Abbreviation');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,2,16,'Differentiation');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,17,'Association');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,3,18,'Numerical reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,1,19,'Numerical reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (14,2,20,'Verbal reasoning');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,3,1,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,2,2,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,4,3,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,1,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,2,5,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,4,6,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,2,7,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,1,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,1,9,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,2,10,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,4,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,3,12,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,2,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,1,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,1,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,3,16,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,3,17,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,2,18,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,3,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (15,4,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,1,1,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,4,2,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,4,3,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,1,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,4,5,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,2,6,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,2,7,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,3,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,2,9,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,1,10,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,2,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,3,12,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,2,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,3,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,4,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,1,16,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,2,17,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,3,18,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,2,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (16,4,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,2,1,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,2,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,3,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,2,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,1,5,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,4,6,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,7,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,9,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,4,10,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,12,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,4,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,16,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,2,17,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,4,18,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,1,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (17,3,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,1,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,2,2,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,1,3,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,2,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,5,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,6,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,3,7,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,2,9,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,2,10,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,3,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,3,12,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,3,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,16,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,2,17,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,4,18,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,3,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (18,1,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,2,1,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,1,2,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,2,3,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,4,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,5,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,1,6,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,4,7,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,9,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,10,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,2,12,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,1,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,4,16,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,17,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,4,18,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,3,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (19,4,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,1,1,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,1,2,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,3,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,3,5,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,4,6,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,7,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,1,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,9,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,4,10,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,12,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,4,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,3,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,4,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,16,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,3,17,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,1,18,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (20,2,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,3,1,'Punctuation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,4,2,'Pronouns');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,1,3,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,3,4,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,1,5,'Vocabulary ');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,2,6,'Vocabulary ');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,2,7,'Vocabulary ');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,2,8,'Vocabulary ');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,4,9,'Vocabulary ');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,4,10,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,2,11,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,1,12,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,4,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,3,14,'Spelling');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,2,15,'Composition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,1,16,'Synoyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,3,17,'Synoyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,3,18,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,4,19,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (21,2,20,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,1,1,'Synonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,3,2,'Synonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,2,3,'Synonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,3,4,'Punctauation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,4,5,'Punctauation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,4,6,'Punctauation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,1,7,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,3,8,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,4,9,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,2,10,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,1,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,4,12,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,1,13,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,3,14,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,1,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,2,16,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,3,17,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,1,18,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,3,19,'Punctauation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (23,4,20,'Punctauation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,2,1,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,1,2,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,4,3,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,1,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,2,5,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,1,6,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,3,7,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,4,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,3,9,'Synonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,4,10,'Synonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,4,11,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,1,12,'Grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,3,13,'Punctuation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,2,14,'Punctuation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,1,15,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,4,16,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,2,17,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,4,18,'Antonyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,4,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (24,2,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,4,1,'Punctuation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,4,2,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,4,3,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,2,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,3,5,'Spelling ');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,2,6,'Composition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,2,7,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,3,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,4,9,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,2,10,'Sentences');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,2,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,3,12,'Sentences');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,2,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,2,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,4,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,1,16,'Synoyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,3,17,'Synoyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,3,18,'Composition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,3,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (1,1,20,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,4,1,'Punctuation, grammar');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,4,2,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,4,3,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,2,4,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,3,5,'Spelling ');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,2,6,'Composition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,2,7,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,3,8,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,4,9,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,2,10,'Sentences');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,2,11,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,3,12,'Sentences');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,2,13,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,2,14,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,4,15,'Comprehension');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,1,16,'Synoyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,3,17,'Synoyms');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,3,18,'Composition');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,3,19,'Vocabulary');
INSERT INTO jac.AssessmentAnswerCollection (`AssessmentAnswer_id`,`answer`,`question`,`topic`) VALUES (22,1,20,'Vocabulary');

Commit;