INSERT INTO jae.Book (name, grade, price,registerDate) VALUES ('[V1] Primary Workbooks','1', 65, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Primary Workbooks','1', 65, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Primary Workbooks','1', 65, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Primary Workbooks','1', 65, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Primary Workbooks','1', 65, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Primary Workbooks','1', 13, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Primary Workbooks','2', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Primary Workbooks','2', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Primary Workbooks','2', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Primary Workbooks','2', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Primary Workbooks','2', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Primary Workbooks','2', 13, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Writing Practice','2', 5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Primary Workbooks','3', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Primary Workbooks','3', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Primary Workbooks','3', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Primary Workbooks','3', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Primary Workbooks','3', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Primary Workbooks','3', 13, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Writing Practice','3', 5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Primary Workbooks','4', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Primary Workbooks','4', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Primary Workbooks','4', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Primary Workbooks','4', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Primary Workbooks','4', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Primary Workbooks','4', 13, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Writing Practice','4', 5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Primary Workbooks','5', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Primary Workbooks','5', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Primary Workbooks','5', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Primary Workbooks','5', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Primary Workbooks','5', 70, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Primary Workbooks','5', 13, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Writing Practice','5', 5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Secondary Workbooks','6', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Secondary Workbooks','6', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Secondary Workbooks','6', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Secondary Workbooks','6', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Secondary Workbooks','6', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('English Workbook','6', 18.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Maths WB & HW','6', 30.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Pearson Science','6', 65.95, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Secondary Workbooks','7', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Secondary Workbooks','7', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Secondary Workbooks','7', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Secondary Workbooks','7', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Secondary Workbooks','7', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('English Workbook','7', 18.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Maths WB & HW','7', 30.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Pearson Science','7', 65.95, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Secondary Workbooks','8', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Secondary Workbooks','8', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Secondary Workbooks','8', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Secondary Workbooks','8', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Secondary Workbooks','8', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('English Workbook','8', 18.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Maths WB & HW','8', 30.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Pearson Science','8', 65.95, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] Secondary Workbooks','9', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] Secondary Workbooks','9', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] Secondary Workbooks','9', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] Secondary Workbooks','9', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] Secondary Workbooks','9', 49, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('English Workbook','9', 18.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Maths WB & HW','9', 30.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Pearson Science','9', 65.95, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] TT6 & FT6','11', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] TT6 & FT6','11', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] TT6 & FT6','11', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] TT6 & FT6','11', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] TT6 & FT6','11', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] TT6','11', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] TT6','11', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] TT6','11', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] TT6','11', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] TT6','11', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] FT6 - English','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] FT6 - Mathmatics','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] FT6 - English','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] FT6 - Mathmatics','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] FT6 - English','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] FT6 - Mathmatics','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] FT6 - English','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] FT6 - Mathmatics','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] FT6 - English','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] FT6- Mathmatics','11', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('GA','11', 22.95, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] TT8 & FT8','12', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] TT8 & FT8','12', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] TT8 & FT8','12', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] TT8 & FT8','12', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] TT8 & FT8','12', 66, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] TT8','12', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] TT8','12', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] TT8','12', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] TT8','12', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] TT8','12', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] FT8 - English','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] FT8 - Mathmatics','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] FT8 - English','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] FT8 - Mathmatics','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] FT8 - English','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] FT8 - Mathmatics','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] FT8 - English','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] FT8 - Mathmatics','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] FT8 - English','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] FT8- Mathmatics','12', 16.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Successful Comprehension','12', 31.95, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] SRW','16', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] SRW','16', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] SRW','16', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] SRW','16', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] SRW','16', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] SRW','18', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] SRW','18', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] SRW','18', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V4] SRW','18', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V5] SRW','18', 14.5, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V1] JMSS','19', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V2] JMSS','19', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('[V3] JMSS','19', 33, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('VCE Book','20', 1, CURDATE());
INSERT INTO jae.Book (name, grade, price, registerDate) VALUES ('Postage','all', 9.99, CURDATE());
COMMIT;