INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P2 Onsite','p2', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P2 Online','p2', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P3 Onsite','p3', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P3 Online','p3', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P4 Onsite','p4', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P4 Online','p4', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P5 Onsite','p5', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P5 Online','p5', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P6 Onsite','p6', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('P6 Online','p6', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S7 Onsite','s7', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S7 Onsite','s7', 'Onsite 2 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S7 Onsite','s7', 'Onsite 1 Subject', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S7 Online','s7', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S8 Onsite','s8', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S8 Onsite','s8', 'Onsite 2 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S8 Onsite','s8', 'Onsite 1 Subject', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S8 Online','s8', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S9 Onsite','s9', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S9 Onsite','s9', 'Onsite 2 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S9 Onsite','s9', 'Onsite 1 Subject', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S9 Online','s9', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S10 Onsite','s10', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S10 Onsite','s10', 'Onsite 2 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S10 Onsite','s10', 'Onsite 1 Subject', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S10 Online','s10', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('S10E Onsite','s10e', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('TT6 Onsite','tt6', 'Onsite TT6 Course', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('TT6 Online','tt6', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('TT8 Onsite','tt8', 'Onsite TT8 Course', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('TT8 Online','tt8', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('TT8E Onsite','tt8e', 'Onsite TT8E Course', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('TT8E Online','tt8e', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('SRW4','srw4', '[P4] Writing', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('SRW5','srw5', '[P5] Writing', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('SRW6','srw6', '[TT6] Writing', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('SRW8','srw8', '[TT8] Writing', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('JMSS Onsite','jmss', 'Onsite JMSS Course', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('JMSS Online','jmss', 'Online Class', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('VCE 3 Sub','vce', 'Onsite 3 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('VCE 2 Sub','vce', 'Onsite 2 Subjects', 70 , CURDATE());
INSERT INTO jae.Course (name, grade,description, price, registerDate) VALUES ('VCE 1 Sub','vce', 'Onsite 1 Subject', 70 , CURDATE());

COMMIT;
