name: Build and deploy WAR app to Azure Web App - jac-spring

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Check current directory structure
        run: ls -la

      - name: Build with Maven
        run: mvn clean install

      - name: Check target directory structure after build
        run: |
          echo "Listing target directory after build:"
          ls -la target

      - name: Rename WAR file to ROOT.war
        run: |
          if [ -d target ]; then
            mv target/*.war target/ROOT.war
          else
            echo "Target directory does not exist"
            exit 1
          fi

      - name: Check target directory structure after renaming
        run: |
          echo "Listing target directory after renaming:"
          ls -la target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: target/ROOT.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: List downloaded files
        run: |
          echo "Listing target directory after download:"
          ls -la target

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B2A096942A8A4B1E86B43763FCA0CF19 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_77FE9E736B194F2F8A274B2E0888526A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5187BDE6FF72413991C1F1AE54BE2AF3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jac-management'
          slot-name: 'Production'
          package: target/ROOT.war